---
name: '[CD] to PyPI'

on:
  release:
    types:
      - published

jobs:
  deliver_to_pypi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Build version
        run: |
          echo "BUILD_VER=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Install python3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install poetry
        run: |
          curl -sSL \
            "https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py" | python
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Deliver a new release (first dry run)
        run: |
          test v$(poetry version -s) = ${{ env.BUILD_VER }}
          poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }} --dry-run
          poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
